// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZGz0_uJfHKM7divb652Z031flqBXtWY',
    appId: '1:1076765477922:web:a19e89c52fbfba86908e7b',
    messagingSenderId: '1076765477922',
    projectId: 'fnc-portal-bd8fd',
    authDomain: 'fnc-portal-bd8fd.firebaseapp.com',
    storageBucket: 'fnc-portal-bd8fd.firebasestorage.app',
    measurementId: 'G-099JLF5C46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcde7jPB9xALWZ0zz1_OtB8CJzhLwLDE4',
    appId: '1:1076765477922:android:e8d931c9d0c66302908e7b',
    messagingSenderId: '1076765477922',
    projectId: 'fnc-portal-bd8fd',
    storageBucket: 'fnc-portal-bd8fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9FjM-isqo1fF0BOPivij0Wz4HE0D5HsE',
    appId: '1:1076765477922:ios:058b4c46a30bceac908e7b',
    messagingSenderId: '1076765477922',
    projectId: 'fnc-portal-bd8fd',
    storageBucket: 'fnc-portal-bd8fd.firebasestorage.app',
    iosBundleId: 'com.example.fncPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXZGz0_uJfHKM7divb652Z031flqBXtWY',
    appId: '1:1076765477922:web:51e77cd951a84556908e7b',
    messagingSenderId: '1076765477922',
    projectId: 'fnc-portal-bd8fd',
    authDomain: 'fnc-portal-bd8fd.firebaseapp.com',
    storageBucket: 'fnc-portal-bd8fd.firebasestorage.app',
    measurementId: 'G-DBD7FGM0LN',
  );
}
